// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoFinalTPI.Backend.Data;

#nullable disable

namespace ProyectoFinalTPI.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261003141727_AgregarEntidadComentario2")]
    partial class AgregarEntidadComentario2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaOculto")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Lugar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Coordenadas")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lugar");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Moderación", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaResuelto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JustificacionModerador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Motivo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Moderacion");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("integer");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaOculto")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreación")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LugarId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoOculto")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LugarId");

                    b.ToTable("Publicacion");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo_usuario")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasDiscriminator<string>("tipo_usuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Usuario_Interactivo", b =>
                {
                    b.HasBaseType("ProyectoFinalTPI.Backend.Entidades.Usuario");

                    b.Property<int>("PuntosNostalgia")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SuspendidoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Usuario_Interactivo");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Usuario_Marca", b =>
                {
                    b.HasBaseType("ProyectoFinalTPI.Backend.Entidades.Usuario_Interactivo");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebOficial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Marca");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Usuario_Personal", b =>
                {
                    b.HasBaseType("ProyectoFinalTPI.Backend.Entidades.Usuario_Interactivo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reputacion")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Personal");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Moderador", b =>
                {
                    b.HasBaseType("ProyectoFinalTPI.Backend.Entidades.Usuario_Personal");

                    b.Property<DateTime>("FechaAscenso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReportesAtendidos")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Moderador");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Comentario", b =>
                {
                    b.HasOne("ProyectoFinalTPI.Backend.Entidades.Publicacion", "Publicacion")
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinalTPI.Backend.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Publicacion", b =>
                {
                    b.HasOne("ProyectoFinalTPI.Backend.Entidades.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("LugarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Publicacion", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
