// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoFinalTPI.Backend.Repositorio.Data;

#nullable disable

namespace ProyectoFinalTPI.Backend.Repositorio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaOculto")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Lugar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Coordenadas")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("lugares", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.441 -34.618)"),
                            Direccion = "Caballito, Buenos Aires",
                            Nombre = "Caballito, Buenos Aires"
                        },
                        new
                        {
                            Id = 2,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.392 -34.6045)"),
                            Direccion = "Avenida Corrientes y Callao, Buenos Aires",
                            Nombre = "Avenida Corrientes y Callao, Buenos Aires"
                        },
                        new
                        {
                            Id = 3,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.565 -34.644)"),
                            Direccion = "Plaza San Martín, Ramos Mejía, Buenos Aires",
                            Nombre = "Plaza San Martín, Ramos Mejía, Buenos Aires"
                        },
                        new
                        {
                            Id = 4,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.4355 -34.6065)"),
                            Direccion = "Parque Centenario, Caballito, Buenos Aires",
                            Nombre = "Parque Centenario, Caballito, Buenos Aires"
                        },
                        new
                        {
                            Id = 5,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-60.6304 -32.9475)"),
                            Direccion = "Monumento Nacional a la Bandera, Rosario",
                            Nombre = "Monumento Nacional a la Bandera, Rosario"
                        },
                        new
                        {
                            Id = 6,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-64.1835 -31.4167)"),
                            Direccion = "Plaza San Martín, centro de Córdoba",
                            Nombre = "Plaza San Martín, centro de Córdoba"
                        },
                        new
                        {
                            Id = 7,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-68.8794 -32.8951)"),
                            Direccion = "Lago del Parque General San Martín, Mendoza",
                            Nombre = "Lago del Parque General San Martín, Mendoza"
                        },
                        new
                        {
                            Id = 8,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-57.5433 -38.0068)"),
                            Direccion = "Plaza Colón, centro de Mar del Plata",
                            Nombre = "Plaza Colón, centro de Mar del Plata"
                        },
                        new
                        {
                            Id = 9,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-71.3102 -41.1335)"),
                            Direccion = "Centro Cívico, San Carlos de Bariloche",
                            Nombre = "Centro Cívico, San Carlos de Bariloche"
                        },
                        new
                        {
                            Id = 10,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-65.4103 -24.7892)"),
                            Direccion = "Plaza 9 de Julio, centro de Salta",
                            Nombre = "Plaza 9 de Julio, centro de Salta"
                        },
                        new
                        {
                            Id = 11,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.56 -34.676)"),
                            Direccion = "San Justo, La Matanza",
                            Nombre = "San Justo, La Matanza"
                        },
                        new
                        {
                            Id = 12,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.565 -34.644)"),
                            Direccion = "Ramos Mejía, Buenos Aires",
                            Nombre = "Ramos Mejía, Buenos Aires"
                        },
                        new
                        {
                            Id = 13,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.619 -34.65)"),
                            Direccion = "Morón, Buenos Aires",
                            Nombre = "Morón, Buenos Aires"
                        },
                        new
                        {
                            Id = 14,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.56 -34.676)"),
                            Direccion = "Plaza Sarmiento, San Justo, Buenos Aires",
                            Nombre = "Plaza Sarmiento, San Justo, Buenos Aires"
                        },
                        new
                        {
                            Id = 15,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.562816626446505 -34.67077213671422)"),
                            Direccion = "universidad Nacional De La Matanza",
                            Nombre = "universidad Nacional De La Matanza"
                        },
                        new
                        {
                            Id = 16,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.4108 -34.6035)"),
                            Direccion = "Abasto, Buenos Aires",
                            Nombre = "Abasto, Buenos Aires"
                        },
                        new
                        {
                            Id = 17,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.557 -34.682)"),
                            Direccion = "Cine de San Justo, Buenos Aires",
                            Nombre = "Cine de San Justo, Buenos Aires"
                        },
                        new
                        {
                            Id = 18,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.584 -34.657)"),
                            Direccion = "Villa Luzuriaga, La Matanza, Buenos Aires",
                            Nombre = "Villa Luzuriaga, La Matanza, Buenos Aires"
                        },
                        new
                        {
                            Id = 19,
                            Coordenadas = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-58.5034528673788 -34.673563442734945)"),
                            Direccion = "Bajada Gral. Paz Crovara",
                            Nombre = "Bajada Gral. Paz Crovara"
                        });
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Moderación", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaResuelto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JustificacionModerador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Motivo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Moderaciones");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstaOculto")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreación")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LugarId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoOculto")
                        .HasColumnType("text");

                    b.Property<int?>("PublicacionOriginalId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoMultimedia")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlMultimedia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LugarId");

                    b.HasIndex("PublicacionOriginalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Publicaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = 1,
                            Descripcion = "Nos juntábamos en el living de un amigo con un disco de Sui Generis. Antes de apoyar la púa, alguien pedía silencio y otro acomodaba los almohadones en el piso. Leíamos la funda mientras sonaba el lado A y discutíamos quién daba vuelta el disco. No teníamos una colección grande: por eso conocíamos hasta los pequeños ruidos de cada vinilo. ¿Qué disco escuchaban sin saltarse un tema?",
                            EstaOculto = false,
                            Fecha = new DateTime(1973, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(7643),
                            LugarId = 1,
                            TipoMultimedia = 0,
                            Titulo = "El vinilo que escuchábamos de principio a fin",
                            UrlMultimedia = "",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Categoria = 1,
                            Descripcion = "Salimos a recorrer disquerías con unas monedas juntadas durante el mes. Mi hermano buscaba rock y yo miraba las portadas como si fueran cuadros. Volvimos con un disco usado y la promesa de prestarlo el fin de semana. En el colectivo llevé la bolsa contra el pecho para que no se doblara la funda. Al llegar a casa despejamos la mesa y armamos nuestra pequeña ceremonia alrededor del tocadiscos.",
                            EstaOculto = false,
                            Fecha = new DateTime(1976, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9083),
                            LugarId = 2,
                            TipoMultimedia = 0,
                            Titulo = "La bolsa de discos de la avenida Corrientes",
                            UrlMultimedia = "",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Categoria = 1,
                            Descripcion = "Nos encontramos en la plaza con los discos envueltos en papel. Cada uno había escrito su nombre en una esquina de la funda para acordarnos de devolverlos. Cambié uno de mis favoritos por un álbum que no había escuchado nunca. Esa tarde fui directo al equipo de música y me quedé siguiendo las letras hasta que oscureció. Todavía recuerdo la emoción de descubrir canciones gracias a los amigos.",
                            EstaOculto = false,
                            Fecha = new DateTime(1978, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9130),
                            LugarId = 3,
                            TipoMultimedia = 0,
                            Titulo = "Un domingo para intercambiar vinilos",
                            UrlMultimedia = "",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Categoria = 0,
                            Descripcion = "Nos sentamos en un banco del Parque Centenario, en Caballito, para planear las vacaciones. Papá desplegó el mapa de rutas sobre las rodillas y mamá marcó con lápiz los pueblos donde podíamos parar. Yo sujetaba una esquina para que no se volara. Después dimos una vuelta al lago y compramos maní. Guardamos aquel mapa doblado en la guantera; años después todavía tenía la mancha redonda del termo.",
                            EstaOculto = false,
                            Fecha = new DateTime(1972, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9168),
                            LugarId = 4,
                            TipoMultimedia = 0,
                            Titulo = "El mapa abierto junto al lago",
                            UrlMultimedia = "",
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            Categoria = 1,
                            Descripcion = "Me encontré con mi hermana en las escalinatas del Monumento a la Bandera, en Rosario. Venía con un disco nuevo bajo el brazo, envuelto en una bolsa de papel que no quería apoyar en el suelo. Nos quedamos mirando el Paraná mientras me contaba qué tema íbamos a escuchar primero. Volvimos caminando a casa y corrimos las sillas del comedor. Lo que más recuerdo es el cuidado con que bajó la púa.",
                            EstaOculto = false,
                            Fecha = new DateTime(1976, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9238),
                            LugarId = 5,
                            TipoMultimedia = 0,
                            Titulo = "La bolsa de discos frente al río",
                            UrlMultimedia = "",
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 6,
                            Categoria = 6,
                            Descripcion = "La abuela nos esperaba en la Plaza San Martín de Córdoba con una revista doblada dentro de la cartera. Nos sentamos frente a la Catedral y nos mostró una receta que quería probar el domingo. Mi prima se quedó mirando las publicidades y yo copié los ingredientes en un papel. Al volver compramos harina y huevos. El bizcochuelo salió torcido, pero guardamos el recorte entre las páginas de su cuaderno.",
                            EstaOculto = false,
                            Fecha = new DateTime(1974, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9280),
                            LugarId = 6,
                            TipoMultimedia = 0,
                            Titulo = "La revista que pasó de mano en mano",
                            UrlMultimedia = "",
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 7,
                            Categoria = 5,
                            Descripcion = "Para el aniversario de mis padres llevamos una mesa plegable al lago del Parque General San Martín, en Mendoza. Mis tíos llegaron con empanadas y mi hermana preparó un cartel pintado con témpera. Antes de almorzar nos acomodamos para una foto con la cámara de rollo. El disparador tardó tanto que papá salió corriendo a comprobarlo. En la copia aparece de espaldas y el resto de nosotros riéndose.",
                            EstaOculto = false,
                            Fecha = new DateTime(1975, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9312),
                            LugarId = 7,
                            TipoMultimedia = 0,
                            Titulo = "El aniversario bajo los árboles",
                            UrlMultimedia = "",
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 8,
                            Categoria = 2,
                            Descripcion = "En las vacaciones de Mar del Plata nos reuníamos en Plaza Colón después de la merienda. Una tarde mi tío llevó el diario y rodeó con birome tres horarios de cine. Cada primo votó por una película distinta y terminamos decidiendo por la que nos dejaba volver temprano a cenar. Conservé la página doblada como señalador durante meses. Hoy no recuerdo qué sala elegimos, pero sí aquella discusión en el banco.",
                            EstaOculto = false,
                            Fecha = new DateTime(1978, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9342),
                            LugarId = 8,
                            TipoMultimedia = 0,
                            Titulo = "La cartelera anotada en el diario",
                            UrlMultimedia = "",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 9,
                            Categoria = 3,
                            Descripcion = "En el Centro Cívico de Bariloche compré una postal para mis abuelos. Habíamos visto paisajes de montañas en su televisor en blanco y negro y quería contarles cómo eran los colores de verdad. Me senté debajo de los arcos a escribir mientras mamá buscaba una estampilla. Dibujé un pequeño sol junto al saludo. Cuando regresamos, la postal estaba apoyada sobre el televisor, al lado del retrato de casamiento.",
                            EstaOculto = false,
                            Fecha = new DateTime(1973, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9371),
                            LugarId = 9,
                            TipoMultimedia = 0,
                            Titulo = "La postal para contar el viaje",
                            UrlMultimedia = "",
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 10,
                            Categoria = 4,
                            Descripcion = "Mi primo trajo a Salta una revista con una nota sobre juegos electrónicos. La leímos sentados en la Plaza 9 de Julio, frente al Cabildo. Ninguno tenía una consola, así que copiamos la pantalla en un cuaderno e inventamos reglas para jugar con el lápiz. Cada cuadradito era un punto y el que se salía perdía el turno. La abuela nos llamó para merendar y seguimos discutiendo el puntaje hasta llegar a casa.",
                            EstaOculto = false,
                            Fecha = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9400),
                            LugarId = 10,
                            TipoMultimedia = 0,
                            Titulo = "La maquinita dibujada en el cuaderno",
                            UrlMultimedia = "",
                            UsuarioId = 9
                        },
                        new
                        {
                            Id = 11,
                            Categoria = 6,
                            Descripcion = "Cada domingo lavábamos el Renault 12 de papá antes de salir. Yo alcanzaba el balde y mi hermana elegía el cassette. Todavía recuerdo los asientos calientes por el sol y el ruido de la puerta del garaje. Parábamos en la plaza de San Justo a comprar algo fresco antes de volver. ¿Qué auto los llevaba de paseo en esa época?",
                            EstaOculto = false,
                            Fecha = new DateTime(1982, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9429),
                            LugarId = 11,
                            TipoMultimedia = 0,
                            Titulo = "El Renault 12 de los domingos",
                            UrlMultimedia = "https://www.testdelayer.com.ar/industria/renault-12-l.JPG",
                            UsuarioId = 10
                        },
                        new
                        {
                            Id = 12,
                            Categoria = 6,
                            Descripcion = "Compramos un Fiat 128 usado entre ahorros y ayuda de la familia. Tenía el volante gastado y una radio que había que acomodar con paciencia. Ese primer viaje con amigos fue inolvidable. Salimos de Ramos Mejía con un mapa de papel y una bolsa de sándwiches. Nos perdimos un par de veces y volvimos de noche, cansados pero felices de tener nuestra propia aventura.",
                            EstaOculto = false,
                            Fecha = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9458),
                            LugarId = 12,
                            TipoMultimedia = 0,
                            Titulo = "Mi primer viaje en un Fiat 128",
                            UrlMultimedia = "https://www.carrosyclasicos.com/imagenes/cronicas/fiat_128/1970.jpg",
                            UsuarioId = 11
                        },
                        new
                        {
                            Id = 13,
                            Categoria = 6,
                            Descripcion = "Los sábados nos juntábamos a charlar de autos en la esquina. El Falcon de mi tío siempre terminaba con el capó abierto y todo el mundo dando consejos. Después cerrábamos el capó y nos quedábamos hablando hasta que anochecía en Morón. A veces aparecía algún vecino con fotos de su último viaje y las pasábamos de mano en mano. Compartan qué modelo recuerdan de su barrio.",
                            EstaOculto = false,
                            Fecha = new DateTime(1987, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9526),
                            LugarId = 13,
                            TipoMultimedia = 0,
                            Titulo = "El Falcon y las reuniones del barrio",
                            UrlMultimedia = "https://www.infobae.com/resizer/v2/VUXHXB5EHFGJFCAYE4325BPSLI.jpg?auth=2a99706702c8c5f0adf0ce3e15940db0c784b3b86474c537a3d5041407d44c27&smart=true&width=350&height=197&quality=85",
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 14,
                            Categoria = 1,
                            Descripcion = "Fuimos un domingo de septiembre al Parque Centenario, en Caballito. Mi hermano llevaba su walkman en una riñonera y me prestó un auricular mientras dábamos la vuelta al lago. Había grabado canciones de la radio: entre tema y tema se escuchaba al locutor. Nos sentamos en el pasto, compartimos una mandarina y anotamos en la cajita qué canciones queríamos conseguir completas. Cada vez que veo un cassette me acuerdo de esa caminata.",
                            EstaOculto = false,
                            Fecha = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9554),
                            LugarId = 4,
                            TipoMultimedia = 0,
                            Titulo = "El walkman de mi hermano en Centenario",
                            UrlMultimedia = "https://ichef.bbci.co.uk/ace/ws/640/amz/worldservice/live/assets/images/2009/06/29/090629181016_sp_walkman_226.jpg.webp",
                            UsuarioId = 12
                        },
                        new
                        {
                            Id = 15,
                            Categoria = 0,
                            Descripcion = "La seño nos llevó al Monumento a la Bandera, en Rosario, en una salida de cuarto grado. Mi mamá me había preparado dos sanguchitos envueltos en una servilleta y una naranja. Subimos los escalones en fila, buscamos el río entre las columnas y después dibujamos el monumento sentados en nuestros abrigos. En mi dibujo la torre quedó torcida. Todavía está pegado en el cuaderno de ese año.",
                            EstaOculto = false,
                            Fecha = new DateTime(1983, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9584),
                            LugarId = 5,
                            TipoMultimedia = 0,
                            Titulo = "La excursión al Monumento a la Bandera",
                            UrlMultimedia = "https://planaxia.com/wp-content/uploads/2020/06/monumento-3-300x297.jpeg",
                            UsuarioId = 13
                        },
                        new
                        {
                            Id = 16,
                            Categoria = 6,
                            Descripcion = "Mi papá nos citó en la Plaza San Martín, frente a la Catedral, para empezar las vacaciones con una foto de los cuatro. Mi hermana y yo teníamos el mismo pulóver tejido por la abuela. Cuando levantó la cámara, una paloma pasó tan cerca que nos agachamos. Gastó otra foto, pero al revelar el rollo elegimos la primera: estábamos muertos de risa. Fue nuestra postal familiar de Córdoba.",
                            EstaOculto = false,
                            Fecha = new DateTime(1987, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9612),
                            LugarId = 6,
                            TipoMultimedia = 0,
                            Titulo = "Una foto frente a la Catedral de Córdoba",
                            UrlMultimedia = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbPKUdeZs1zxPT0uKsmYYfQz45mv8auZA-LqKJ6k24ywF_i5RaRTdwZQ&s=100",
                            UsuarioId = 14
                        },
                        new
                        {
                            Id = 17,
                            Categoria = 5,
                            Descripcion = "Festejamos los sesenta de mi abuela al lado del lago del Parque General San Martín, en Mendoza. Mi tío llegó en bicicleta con el pan atado al portaequipaje y mi mamá llevó una torta en una caja de zapatos. Pusimos el mantel a cuadros bajo un árbol y sujetamos las esquinas con cuatro piedras. Cuando sopló las velitas, el viento apagó la mitad antes que ella. La seguimos cargando durante años.",
                            EstaOculto = false,
                            Fecha = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9639),
                            LugarId = 7,
                            TipoMultimedia = 0,
                            Titulo = "El mantel a cuadros junto al lago",
                            UrlMultimedia = "https://media.losandes.com.ar/adjuntos/368/migration/resizer/v2/HE2GGNLGMFQTAYZTMMZTGYLCGI.jpg?auth=b1f853a1f331b171644b38fc350f2b985dd873d56ac7c0da01bb51cb48cd83c6&width=768&height=327",
                            UsuarioId = 15
                        },
                        new
                        {
                            Id = 18,
                            Categoria = 2,
                            Descripcion = "Ese enero nos alojábamos a dos cuadras de Plaza Colón, en Mar del Plata. Una noche salimos del cine y nos quedamos en un banco de la plaza, con los abrigos encima de las rodillas, discutiendo el final de Volver al futuro. Mi primo juraba que algún día los autos iban a volar. Mamá nos compró maní y dejamos que hablara hasta terminar la bolsita. No me acuerdo de la sala, pero sí de esa conversación.",
                            EstaOculto = false,
                            Fecha = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9668),
                            LugarId = 8,
                            TipoMultimedia = 0,
                            Titulo = "El final de la película, en Plaza Colón",
                            UrlMultimedia = "https://cloudfront-us-east-1.images.arcpublishing.com/infobae/KYMFDUWD5FGM3OG3SWLS7QBO5E.jpg",
                            UsuarioId = 16
                        },
                        new
                        {
                            Id = 19,
                            Categoria = 3,
                            Descripcion = "En nuestro primer viaje a Bariloche, mi hermana tenía miedo de perderse su programa de la tarde. Durante la parada en el Centro Cívico, papá hizo de narrador e inventó un capítulo con nosotros como protagonistas. La torre del reloj era un castillo y el lago, un lugar secreto. Nos sacó una foto actuando frente a los arcos. Terminamos olvidándonos de pedir que prendieran la tele en el hotel.",
                            EstaOculto = false,
                            Fecha = new DateTime(1989, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9695),
                            LugarId = 9,
                            TipoMultimedia = 0,
                            Titulo = "El capítulo que contamos en el Centro Cívico",
                            UrlMultimedia = "https://www.patagoniaandina.com/wp-content/uploads/2019/07/centro-civico-bariloche.jpg",
                            UsuarioId = 17
                        },
                        new
                        {
                            Id = 20,
                            Categoria = 4,
                            Descripcion = "Mi primo vino de visita a Salta con una maquinita electrónica de un solo juego. La llevó a la Plaza 9 de Julio después del almuerzo. Elegimos un banco a la sombra, frente al Cabildo, porque al sol no se veía la pantalla. Anotábamos los puntajes en el reverso de un boleto y cada uno tenía tres intentos. Mi abuela nos encontró ahí dos horas después: no habíamos caminado ni una cuadra.",
                            EstaOculto = false,
                            Fecha = new DateTime(1984, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9721),
                            LugarId = 10,
                            TipoMultimedia = 0,
                            Titulo = "Tres intentos bajo los árboles de la plaza",
                            UrlMultimedia = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiMwHTiHGgUzMCfRINBT99rwTTzaglYFjl2HJybwE53zLuE8z3wHxph5c&s=100",
                            UsuarioId = 18
                        },
                        new
                        {
                            Id = 21,
                            Categoria = 1,
                            Descripcion = "Llevé un cassette de Nirvana para prestárselo a un compañero después del colegio. Terminó recorriendo medio curso: cada semana alguien distinto decía que lo tenía en su casa. Cuando volvió, la cajita estaba rajada y la etiqueta tenía nombres escritos con birome. Lo puse en el walkman camino a la plaza y sonaba igual de gastado que siempre. En este grupo quiero encontrar a los que también armaban cadenas de préstamos.",
                            EstaOculto = false,
                            Fecha = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9765),
                            LugarId = 14,
                            TipoMultimedia = 0,
                            Titulo = "El cassette de Nirvana que no volvía nunca",
                            UrlMultimedia = "https://deadaheadrecords.com/wp-content/uploads/2022/09/nirvana-nevermind-cassette-tape-used.jpg",
                            UsuarioId = 17
                        },
                        new
                        {
                            Id = 22,
                            Categoria = 1,
                            Descripcion = "Mi amigo había conseguido un disco de Pearl Jam y nos invitó a escucharlo después de merendar. Bajamos la persiana, corrimos los cuadernos y subimos el volumen hasta que su mamá golpeó la puerta. Nos turnábamos para mirar el librito y adivinar las letras. Volví a casa con una copia en cassette y una lista de canciones anotada en la mochila. Cada vez que las escucho vuelvo a ese cuarto lleno de pósters.",
                            EstaOculto = false,
                            Fecha = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9796),
                            LugarId = 12,
                            TipoMultimedia = 0,
                            Titulo = "Pearl Jam en el cuarto de mi amigo",
                            UrlMultimedia = "https://img.ricardostatic.ch/images/d324e2b5-9720-42ca-9ae4-a33d35328ab6/t_1000x750/cd-pearl-jam",
                            UsuarioId = 19
                        },
                        new
                        {
                            Id = 23,
                            Categoria = 1,
                            Descripcion = "Teníamos una guitarra prestada, una batería bastante incompleta y muchas ganas de tocar temas de Soundgarden y Nirvana. El garaje quedaba tan chico que el cantante casi no podía moverse. Grabábamos los ensayos con un equipo apoyado sobre una caja y después nos reíamos de lo mal que se escuchaba. Nunca salimos de ese barrio, pero los sábados de ensayo eran el mejor momento de la semana.",
                            EstaOculto = false,
                            Fecha = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9825),
                            LugarId = 13,
                            TipoMultimedia = 0,
                            Titulo = "Nuestra banda ensayaba en un garaje",
                            UrlMultimedia = "https://tse2.mm.bing.net/th/id/OIP.RX5OoYTN9cO_0mWEo9iIFQHaEk?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
                            UsuarioId = 20
                        },
                        new
                        {
                            Id = 24,
                            Categoria = 6,
                            Descripcion = "Nos encontrábamos los sábados a las cinco en la entrada del Parque Centenario por la avenida Díaz Vélez, cerca del museo. Yo iba desde Almagro en una bici verde; Juli llevaba el termo y Mariano siempre aparecía con galletitas rotas en la mochila. Dábamos una vuelta al lago y elegíamos el mismo pedazo de pasto para sentarnos. Una tarde nos agarró la lluvia y volvimos pedaleando, con el mate guardado en una bolsa. Todavía tengo la foto que nos sacamos empapados en el palier.",
                            EstaOculto = false,
                            Fecha = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9850),
                            LugarId = 4,
                            TipoMultimedia = 0,
                            Titulo = "La ronda de mate del Parque Centenario",
                            UrlMultimedia = "https://i.pinimg.com/736x/ef/4f/61/ef4f6175d75d28ffebb1e6997fd86a69.jpg",
                            UsuarioId = 21
                        },
                        new
                        {
                            Id = 25,
                            Categoria = 6,
                            Descripcion = "Todavia me acuerdo de aquel 15 de abril, empecé a estudiar en La Matanza y marcó un antes y un despues en mi vida",
                            EstaOculto = false,
                            Fecha = new DateTime(1991, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9876),
                            LugarId = 15,
                            TipoMultimedia = 0,
                            Titulo = "Primer dia en la Universidad",
                            UrlMultimedia = "https://i.postimg.cc/QdMKq3ZV/0f7ca658-ec73-40e1-98fa-39d9e501e3da.png",
                            UsuarioId = 22
                        },
                        new
                        {
                            Id = 26,
                            Categoria = 1,
                            Descripcion = "Con mi amigo Martín terminamos la secundaria y nos regalamos un cassette grabado por cada uno. Nos juntamos a intercambiarlos en las escalinatas del Monumento a la Bandera, mirando hacia el Paraná. El suyo empezaba con rock nacional y tenía una lista escrita con birome azul. Escuchamos un lado entero compartiendo auriculares, mientras comíamos bizcochitos. En la etiqueta del mío puso “Rosario, diciembre del 93”. Lo conservé aunque después dejé de tener dónde escucharlo.",
                            EstaOculto = false,
                            Fecha = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9902),
                            LugarId = 5,
                            TipoMultimedia = 0,
                            Titulo = "Una cinta y las escalinatas del Monumento",
                            UrlMultimedia = "https://tse1.mm.bing.net/th/id/OIP.Mii6dAY850cL2zGTAUCSfAHaFj?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
                            UsuarioId = 23
                        },
                        new
                        {
                            Id = 27,
                            Categoria = 0,
                            Descripcion = "Quedamos en la Plaza San Martín de Córdoba para organizar nuestro primer viaje a las sierras sin los grandes. Nos sentamos en un banco frente a la Catedral con un mapa de papel y una libreta para sumar los gastos. Teníamos plata para el pasaje y muy poco más. Terminamos eligiendo llevar comida desde casa y repartir las bolsas. Cada vez que vuelvo a esa plaza me acuerdo de lo importante que nos sentíamos haciendo las cuentas.",
                            EstaOculto = false,
                            Fecha = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9929),
                            LugarId = 6,
                            TipoMultimedia = 0,
                            Titulo = "La plaza antes del primer viaje solos",
                            UrlMultimedia = "",
                            UsuarioId = 24
                        },
                        new
                        {
                            Id = 28,
                            Categoria = 5,
                            Descripcion = "Mi hermana cumplió diez y pidió festejar en el Parque General San Martín, cerca del lago. Fuimos temprano a Mendoza a buscar sombra; mi viejo llevó las sillas plegables y yo me encargué de inflar quince globos amarillos. Armamos una búsqueda del tesoro con pistas escritas a mano. El premio estaba en la conservadora, debajo de las gaseosas. En la foto final se ve a Sofi con la corona de cartulina y toda la boca pintada de merengue.",
                            EstaOculto = false,
                            Fecha = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9957),
                            LugarId = 7,
                            TipoMultimedia = 0,
                            Titulo = "Los diez años de Sofi al lado del lago",
                            UrlMultimedia = "",
                            UsuarioId = 25
                        },
                        new
                        {
                            Id = 29,
                            Categoria = 2,
                            Descripcion = "El departamento de vacaciones quedaba cerca de Plaza Colón, en Mar del Plata. Habíamos llevado la videocasetera porque anunciaban lluvia. El primer día nos sentamos en la plaza a escribir qué películas quería ver cada uno: mi hermano pidió Toy Story y mi papá una de aventuras. La lista quedó en una servilleta llena de arena. Al final vimos la misma cinta dos noches seguidas porque nos olvidamos de devolverla.",
                            EstaOculto = false,
                            Fecha = new DateTime(1996, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 704, DateTimeKind.Utc).AddTicks(9998),
                            LugarId = 8,
                            TipoMultimedia = 0,
                            Titulo = "La lista del videoclub en una servilleta",
                            UrlMultimedia = "",
                            UsuarioId = 26
                        },
                        new
                        {
                            Id = 30,
                            Categoria = 3,
                            Descripcion = "La foto de nuestro viaje de egresados se hizo en el Centro Cívico de Bariloche, debajo de los arcos. Mientras esperábamos a los que habían ido a comprar chocolate, empezamos a repartir personajes de una comedia de televisión inventada. El profe quedó como el vecino que se quejaba del ruido y actuó tan bien que nadie podía ponerse serio. El fotógrafo tuvo que esperar. La copia que guardé tiene nuestros nombres escritos atrás.",
                            EstaOculto = false,
                            Fecha = new DateTime(1992, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(29),
                            LugarId = 9,
                            TipoMultimedia = 0,
                            Titulo = "Una sitcom inventada en Bariloche",
                            UrlMultimedia = "",
                            UsuarioId = 27
                        },
                        new
                        {
                            Id = 31,
                            Categoria = 4,
                            Descripcion = "Llevé mi Game Boy a la Plaza 9 de Julio de Salta una tarde de las vacaciones de invierno. Nos sentamos cerca del Cabildo, donde daba el sol, con cuatro pilas de repuesto y una libreta para los récords. Mi prima, que decía que no sabía jugar, nos ganó a todos en Tetris. Le prometimos un helado si repetía la marca y lo hizo en la partida siguiente. Todavía me lo recuerda cada vez que nos vemos.",
                            EstaOculto = false,
                            Fecha = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(54),
                            LugarId = 10,
                            TipoMultimedia = 0,
                            Titulo = "El récord de la Game Boy en Plaza 9 de Julio",
                            UrlMultimedia = "",
                            UsuarioId = 28
                        },
                        new
                        {
                            Id = 32,
                            Categoria = 2,
                            Descripcion = "Fuimos con mis amigos a ver El retorno del rey y llegamos mucho antes para conseguir lugar juntos. En la fila discutimos nuestras escenas favoritas de las películas anteriores, cuidando de no contar nada a quienes no las habían visto. Salimos hablando todos a la vez y terminamos comiendo una pizza mientras repasábamos el final. Guardé la entrada dentro de un libro; todavía tiene una mancha del vaso de gaseosa.",
                            EstaOculto = false,
                            Fecha = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(81),
                            LugarId = 16,
                            TipoMultimedia = 0,
                            Titulo = "La fila para ver El retorno del rey",
                            UrlMultimedia = "",
                            UsuarioId = 27
                        },
                        new
                        {
                            Id = 33,
                            Categoria = 2,
                            Descripcion = "Habíamos organizado toda la semana la salida para ver Harry Potter y el cáliz de fuego. Uno compró las entradas, otro juntó la plata y yo llevé una cámara digital para la foto antes de entrar. Compartimos un balde de pochoclos que se terminó demasiado rápido. A la salida discutimos las diferencias con el libro hasta perder el colectivo. La película era la excusa perfecta para estar juntos un rato más.",
                            EstaOculto = false,
                            Fecha = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(110),
                            LugarId = 17,
                            TipoMultimedia = 0,
                            Titulo = "Harry Potter y una salida después del colegio",
                            UrlMultimedia = "",
                            UsuarioId = 29
                        },
                        new
                        {
                            Id = 34,
                            Categoria = 2,
                            Descripcion = "Alquilamos Shrek en DVD para una noche de películas en casa. Éramos tantos que hubo que traer sillas de la cocina y dejar a dos en el piso. Antes de empezar nos entretuvimos recorriendo los menús, algo que todavía nos parecía una novedad. Terminamos repitiendo los chistes durante semanas y prometiendo otra función para el sábado siguiente. Me acuerdo más de las risas del living que de cualquier otra cosa de esa noche.",
                            EstaOculto = false,
                            Fecha = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(149),
                            LugarId = 18,
                            TipoMultimedia = 0,
                            Titulo = "Shrek en DVD y el sillón lleno",
                            UrlMultimedia = "",
                            UsuarioId = 30
                        },
                        new
                        {
                            Id = 35,
                            Categoria = 6,
                            Descripcion = "Nos juntamos en el Parque Centenario después de rendir la última materia. Llevé una cámara digital plateada que usaba dos pilas y una tarjeta donde casi no quedaba espacio. Elegimos el lago de fondo y sacamos la misma foto ocho veces: siempre alguien cerraba los ojos. Esa noche subí una al Fotolog con un marco negro y un texto larguísimo. Mi mejor amiga comentó antes de que terminara de avisarle por Messenger.",
                            EstaOculto = false,
                            Fecha = new DateTime(2007, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(176),
                            LugarId = 4,
                            TipoMultimedia = 0,
                            Titulo = "La foto del Fotolog, junto al lago",
                            UrlMultimedia = "https://quehacerenba.com/wp-content/uploads/2023/07/img_0845.jpg",
                            UsuarioId = 31
                        },
                        new
                        {
                            Id = 36,
                            Categoria = 5,
                            Descripcion = "No me olvido mas de ese dia, nos juntamos todos a la altura de Liniers a esperar al micro con los jugadores que volvian de Cordoba, en el renault 12 que se ve estabamos mis hermanos y yo, estuvimos festejando en la cancha por horas, ya volveran esos tiempos chicago querido",
                            EstaOculto = false,
                            Fecha = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(203),
                            LugarId = 19,
                            TipoMultimedia = 0,
                            Titulo = "Chicago campeón B Nacional",
                            UrlMultimedia = "https://www.soloascenso.com.ar/Noticias/nchicago2001inedito.jpg",
                            UsuarioId = 32
                        },
                        new
                        {
                            Id = 37,
                            Categoria = 1,
                            Descripcion = "Después de mi primera entrevista de trabajo fui con mi novia al Monumento a la Bandera. Nos sentamos en la parte baja de las escalinatas, mirando el Paraná. En mi MP3 de 128 MB entraban pocas canciones, así que las conocíamos de memoria. Compartimos los auriculares y una gaseosa tibia mientras le contaba todas las cosas que creía haber contestado mal. A la semana me llamaron. Para festejar volvimos al mismo lugar.",
                            EstaOculto = false,
                            Fecha = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(228),
                            LugarId = 5,
                            TipoMultimedia = 0,
                            Titulo = "Un auricular cada uno frente al Paraná",
                            UrlMultimedia = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3GEJYv0JMgPY0DBqGcrZxIh-xW6JtHZ4uIuUi3L9U-BgzePheBjJleVlQ&s=10",
                            UsuarioId = 33
                        },
                        new
                        {
                            Id = 38,
                            Categoria = 0,
                            Descripcion = "Mis amigas y yo quedamos en la Plaza San Martín de Córdoba para intercambiar las fotos de una salida del colegio. Llevé las copias impresas en un sobre de laboratorio; algunas tenían los dedos tapando el lente. Nos repartimos las mejores junto a la Catedral y prometimos escanear las otras. Esa noche la conversación siguió por Messenger: cada una se puso una foto distinta y nos mandamos zumbidos hasta que nos mandaron a dormir.",
                            EstaOculto = false,
                            Fecha = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(254),
                            LugarId = 6,
                            TipoMultimedia = 0,
                            Titulo = "Nos encontramos antes de conectarnos",
                            UrlMultimedia = "https://upload.wikimedia.org/wikipedia/commons/b/bf/Plaza_San_Mart%C3%ADn_C%C3%B3rdoba_2011-03-06.jpg?utm_source=es.wikipedia.org&utm_campaign=index&utm_content=original",
                            UsuarioId = 34
                        },
                        new
                        {
                            Id = 39,
                            Categoria = 5,
                            Descripcion = "Armamos un grupo para reencontrarnos cinco años después de terminar el colegio. Elegimos el lago del Parque General San Martín, en Mendoza, porque todos sabíamos llegar. Cada uno llevó algo para el picnic; yo aparecí con el álbum de la fiesta de egresados. Nos pasamos las fotos de mano en mano y repetimos una, en el mismo orden en que estábamos en el colegio. Esta vez entramos todos en el encuadre.",
                            EstaOculto = false,
                            Fecha = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(526),
                            LugarId = 7,
                            TipoMultimedia = 0,
                            Titulo = "El reencuentro del curso en el parque",
                            UrlMultimedia = "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn9bl_UQY-Raa2UYVIC1xJkykrqXqxRFmmr6O7yfKzjQL6Y3wg_mC7pMyTvNmpkFIgSodBffPei509n5RnigPMdE5ZFyBYV3jU61DpgjFjmhhNXx-ZHHiaM07dOiNNrITwFL-U=s1360-w1360-h1020-rw",
                            UsuarioId = 35
                        },
                        new
                        {
                            Id = 40,
                            Categoria = 2,
                            Descripcion = "Salimos del departamento con la sombrilla y llegamos hasta Plaza Colón, en Mar del Plata, antes de que empezara a llover. Nos refugiamos con mis primos y decidimos volver a buscar una película para la tarde. Terminamos viendo Shrek, que habíamos conseguido en video, sentados en colchones en el living. Afuera seguía lloviendo; adentro repartíamos pochoclos en tazas porque no había suficientes bowls. Fue el día de vacaciones que más recordamos.",
                            EstaOculto = false,
                            Fecha = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(557),
                            LugarId = 8,
                            TipoMultimedia = 0,
                            Titulo = "El día que cambiamos playa por Shrek",
                            UrlMultimedia = "https://pbs.twimg.com/media/Fkg5KUrWYAA8pcZ?format=jpg&name=medium",
                            UsuarioId = 19
                        },
                        new
                        {
                            Id = 41,
                            Categoria = 3,
                            Descripcion = "Viajamos a Bariloche con mis hermanos y nos pasamos el trayecto inventando teorías sobre Lost. En el Centro Cívico quisimos sacar una foto como si fuera la portada de nuestra propia serie: caras serias, brazos cruzados y las montañas de fondo. Mi mamá nos cortó los pies en la primera toma. En la segunda se metió papá saludando. Terminamos imprimiendo esa y poniéndole un título con marcador.",
                            EstaOculto = false,
                            Fecha = new DateTime(2006, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(585),
                            LugarId = 9,
                            TipoMultimedia = 0,
                            Titulo = "Una portada de serie en el Centro Cívico",
                            UrlMultimedia = "",
                            UsuarioId = 36
                        },
                        new
                        {
                            Id = 42,
                            Categoria = 4,
                            Descripcion = "Mi hermano estrenó una consola portátil durante las vacaciones en Salta. A la tarde la llevamos a la Plaza 9 de Julio y buscamos un banco frente al Cabildo. Éramos cuatro, así que el que perdía entregaba la consola y elegía quién seguía. La batería se terminó justo cuando estaba por pasar un nivel. Guardamos todo, fuimos a buscar helado y al volver al hotel lo primero que hicimos fue enchufar el cargador.",
                            EstaOculto = false,
                            Fecha = new DateTime(2008, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreación = new DateTime(2026, 10, 10, 0, 37, 47, 705, DateTimeKind.Utc).AddTicks(670),
                            LugarId = 10,
                            TipoMultimedia = 0,
                            Titulo = "Una consola, cuatro turnos y un helado",
                            UrlMultimedia = "",
                            UsuarioId = 37
                        });
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo_usuario")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);

                    b.HasDiscriminator<string>("tipo_usuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Usuario_Interactivo", b =>
                {
                    b.HasBaseType("ProyectoFinalTPI.Backend.Entidades.Usuario");

                    b.Property<int>("PuntosNostalgia")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SuspendidoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Usuario_Interactivo");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Usuario_Marca", b =>
                {
                    b.HasBaseType("ProyectoFinalTPI.Backend.Entidades.Usuario_Interactivo");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebOficial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Usuario_Marca");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Usuario_Personal", b =>
                {
                    b.HasBaseType("ProyectoFinalTPI.Backend.Entidades.Usuario_Interactivo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reputacion")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Usuario_Personal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contraseña = "password123",
                            Email = "miguel@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(439),
                            Username = "miguel",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Miguel",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 2,
                            Contraseña = "password123",
                            Email = "susana@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6051),
                            Username = "susana",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Susana",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 3,
                            Contraseña = "password123",
                            Email = "héctor@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6142),
                            Username = "héctor",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Héctor",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 4,
                            Contraseña = "password123",
                            Email = "elena@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6161),
                            Username = "elena",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Elena",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 5,
                            Contraseña = "password123",
                            Email = "roberto@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6180),
                            Username = "roberto",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Roberto",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 6,
                            Contraseña = "password123",
                            Email = "inés@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6210),
                            Username = "inés",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Inés",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 7,
                            Contraseña = "password123",
                            Email = "raúl@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6245),
                            Username = "raúl",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Raúl",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 8,
                            Contraseña = "password123",
                            Email = "daniel@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6264),
                            Username = "daniel",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Daniel",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 9,
                            Contraseña = "password123",
                            Email = "teresa@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6282),
                            Username = "teresa",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Teresa",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 10,
                            Contraseña = "password123",
                            Email = "ricardo@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6299),
                            Username = "ricardo",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Ricardo",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 11,
                            Contraseña = "password123",
                            Email = "mariela@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6342),
                            Username = "mariela",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Mariela",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 12,
                            Contraseña = "password123",
                            Email = "leo@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6359),
                            Username = "leo",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Leo",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 13,
                            Contraseña = "password123",
                            Email = "clara@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6375),
                            Username = "clara",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Clara",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 14,
                            Contraseña = "password123",
                            Email = "marina@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6393),
                            Username = "marina",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Marina",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 15,
                            Contraseña = "password123",
                            Email = "gustavo@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6420),
                            Username = "gustavo",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Gustavo",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 16,
                            Contraseña = "password123",
                            Email = "paula@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6437),
                            Username = "paula",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Paula",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 17,
                            Contraseña = "password123",
                            Email = "nico@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6454),
                            Username = "nico",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Nico",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 18,
                            Contraseña = "password123",
                            Email = "ana@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6472),
                            Username = "ana",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Ana",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 19,
                            Contraseña = "password123",
                            Email = "vero@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6489),
                            Username = "vero",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Vero",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 20,
                            Contraseña = "password123",
                            Email = "marcos@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6505),
                            Username = "marcos",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Marcos",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 21,
                            Contraseña = "password123",
                            Email = "lucía@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6522),
                            Username = "lucía",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Lucía",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 22,
                            Contraseña = "password123",
                            Email = "fernando@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6539),
                            Username = "fernando",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Fernando",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 23,
                            Contraseña = "password123",
                            Email = "fede@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6555),
                            Username = "fede",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Fede",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 24,
                            Contraseña = "password123",
                            Email = "sole@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6580),
                            Username = "sole",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Sole",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 25,
                            Contraseña = "password123",
                            Email = "diego@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6597),
                            Username = "diego",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Diego",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 26,
                            Contraseña = "password123",
                            Email = "julieta@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6614),
                            Username = "julieta",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Julieta",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 27,
                            Contraseña = "password123",
                            Email = "pablo@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6691),
                            Username = "pablo",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Pablo",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 28,
                            Contraseña = "password123",
                            Email = "mati@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6707),
                            Username = "mati",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Mati",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 29,
                            Contraseña = "password123",
                            Email = "carla@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6725),
                            Username = "carla",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Carla",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 30,
                            Contraseña = "password123",
                            Email = "luciano@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6741),
                            Username = "luciano",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Luciano",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 31,
                            Contraseña = "password123",
                            Email = "cami@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6757),
                            Username = "cami",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Cami",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 32,
                            Contraseña = "password123",
                            Email = "sergio@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6784),
                            Username = "sergio",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Sergio",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 33,
                            Contraseña = "password123",
                            Email = "agus@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6809),
                            Username = "agus",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Agus",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 34,
                            Contraseña = "password123",
                            Email = "flor@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6827),
                            Username = "flor",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Flor",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 35,
                            Contraseña = "password123",
                            Email = "juan@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6844),
                            Username = "juan",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Juan",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 36,
                            Contraseña = "password123",
                            Email = "nacho@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6861),
                            Username = "nacho",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Nacho",
                            Reputacion = 1
                        },
                        new
                        {
                            Id = 37,
                            Contraseña = "password123",
                            Email = "luli@example.com",
                            EsAdmin = false,
                            FechaCreacion = new DateTime(2026, 10, 10, 0, 37, 47, 690, DateTimeKind.Utc).AddTicks(6879),
                            Username = "luli",
                            PuntosNostalgia = 10,
                            Apellido = "",
                            FechaNacimiento = new DateOnly(1980, 1, 1),
                            Nombre = "Luli",
                            Reputacion = 1
                        });
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Moderador", b =>
                {
                    b.HasBaseType("ProyectoFinalTPI.Backend.Entidades.Usuario_Personal");

                    b.Property<DateTime>("FechaAscenso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReportesAtendidos")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Moderador");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Comentario", b =>
                {
                    b.HasOne("ProyectoFinalTPI.Backend.Entidades.Publicacion", "Publicacion")
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinalTPI.Backend.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Publicacion", b =>
                {
                    b.HasOne("ProyectoFinalTPI.Backend.Entidades.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("LugarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinalTPI.Backend.Entidades.Publicacion", "PublicacionOriginal")
                        .WithMany()
                        .HasForeignKey("PublicacionOriginalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProyectoFinalTPI.Backend.Entidades.Usuario_Interactivo", "Usuario")
                        .WithMany("Publicaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");

                    b.Navigation("PublicacionOriginal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Publicacion", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("ProyectoFinalTPI.Backend.Entidades.Usuario_Interactivo", b =>
                {
                    b.Navigation("Publicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
